application: ar-lis
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /tasks/history/.*
  script: weatherHistory.application
- url: /tasks/conditions/.*
  script: conditionBox.application
- url: /tasks/update/.*
  script: updateWbox.application
- url: /.*
  script: weatherbox.application

libraries:
- name: webapp2
  version: latest
- name: numpy
  version: latest
- name: matplotlib
  version: latest
- name: PIL
  version: latest
- name: yaml
  version: latest
